name: Release Workflow

on:
 workflow_dispatch:



jobs:
   release:
     permissions:
       contents: write
       issues: write
       pull-requests: write
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 16
       - name: Install node dependencies
         run: npm install
       - name: Set up Gradle
         uses: gradle/actions/setup-gradle@v3
       - name: Build with Gradle
         run: chmod +x ./gradlew && ./gradlew build
       - name: Run Semantic Release
         run: npx semantic-release
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}



